name: notes_app
description: "A simple notes app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  get_it: ^7.6.8
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  talker_flutter: ^4.1.3
  talker_dio_logger: ^4.1.3
  talker_bloc_logger: ^4.1.3
  json_annotation: ^4.8.1
  auto_route: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
